import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

import { useRouter } from "next/router";
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();
  const router = useRouter();

  if (session) {
    console.log("Sign in successful", session);
    if (!session.user.email.endsWith("@iith.ac.in")) {
      alert("Please sign in with your IITH email");
      signOut();
    }

    // push to generate page or scan page based on email
    router.push(`/generate`);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Qr - Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <button className={styles.card} onClick={() => signIn()}>
            <h2>Login With Google</h2>
          </button>{" "}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          A{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
          &nbsp; Production
        </a>
      </footer>
    </div>
  );
}
